#
# Docker File for Embedded Development Environment of Espressif MCUs
# with esp-idf (e.g. ESP32).
#
# It uses the official ESP-IDF Container image by Espressif, and adds
# extra useful tools (Jlink tools, PlantUML, Pandoc, etc).
#

###############################################################################

# Base OS
# https://github.com/espressif/esp-idf/blob/master/tools/docker/Dockerfile
FROM docker.io/espressif/idf:v6.0.1

# Docker Container User
ARG ARG_CONTAINER_USER
ENV CONTAINER_USER=${ARG_CONTAINER_USER}

###############################################################################

# VSCode Setup (https://code.visualstudio.com/updates)
ARG VSCODE_VERSION="1.121.0"
ARG VSCODE_REPO_URL="https://update.code.visualstudio.com"
ARG VSCODE_PKG_URL="${VSCODE_REPO_URL}/${VSCODE_VERSION}/linux-deb-x64/stable"

# CMake Setup (https://github.com/Kitware/CMake)
# Custom CMake version instead of the one provided by the base image
ARG CMAKE_VERSION="4.3.3"
ARG CMAKE_PKG="cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz"
ARG CMAKE_REPO_URL="https://github.com/Kitware/CMake/releases/download"
ARG CMAKE_PKG_URL="${CMAKE_REPO_URL}/v${CMAKE_VERSION}/${CMAKE_PKG}"

# JLink Tools Setup (https://www.segger.com/downloads/jlink)
ARG JLINK_VERSION="770"
ARG JLINK_PKG="JLink_Linux_V${JLINK_VERSION}_x86_64.deb"
ARG JLINK_REPO_URL="https://www.segger.com/downloads/jlink"
ARG JLINK_PKG_URL="${JLINK_REPO_URL}/${JLINK_PKG}"
ARG JLINK_LICENSE_ACCEPT=\
"accept_license_agreement=accepted&submit=Download+software"

# PlantUML Setup
ARG PLANTUML_VERSION="1.2026.4"
ARG PLANTUML_PKG="plantuml-full-linux-amd64-${PLANTUML_VERSION}.zip"
ARG PLANTUML_REPO_URL="https://github.com/plantuml/plantuml/releases/download"
ARG PLANTUML_PKG_URL=\
"${PLANTUML_REPO_URL}/v${PLANTUML_VERSION}-native/${PLANTUML_PKG}"

# Pandoc Setup
ARG PANDOC_VER="3.9.0.2"
ARG PANDOC_REPO_URL="https://github.com/jgm/pandoc/releases/download"
ARG PANDOC_PKG="pandoc-${PANDOC_VER}-1-amd64.deb"
ARG PANDOC_PKG_URL="${PANDOC_REPO_URL}/${PANDOC_VER}/${PANDOC_PKG}"

###############################################################################

# User root is needed to install the tools and vscode extensions
USER root

# Create user, ssh and workspace directories
RUN useradd -ms /bin/bash ${CONTAINER_USER} && \
    mkdir -p /home/${CONTAINER_USER}/.ssh && \
    mkdir -p /home/${CONTAINER_USER}/workspace

###############################################################################

# Set Environment Variable for no user interaction with APT
ENV DEBIAN_FRONTEND=noninteractive

# Install APT Tools
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        git \
        python3 \
        python3-pip \
        python3-venv \
        gdb \
        make \
        cmake \
        ninja-build \
        pkg-config \
        cppcheck \
        lcov \
        clang-format \
        clang-tidy \
        doxygen \
        curl \
        wget \
        flex \
        bison \
        gperf \
        ccache \
        libffi-dev \
        libssl-dev \
        dfu-util \
        curl \
        unzip \
        gdb-multiarch \
        openocd \
        usbutils \
        libusb-1.0-0-dev \
        libhidapi-dev \
        libftdi1-dev \
        libudev-dev \
        && \
    apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

###############################################################################

# CMake Installation
RUN wget -O cmake.tar.gz "${CMAKE_PKG_URL}" && \
    tar -xvzf cmake.tar.gz -C /tmp && \
    mkdir -p /opt/tools && \
    cp -a /tmp/cmake* /opt/tools/cmake_$CMAKE_VERSION && \
    rm -rf /tmp/cmake* && \
    rm cmake.tar.gz
ENV PATH="/opt/tools/cmake_${CMAKE_VERSION}/bin:${PATH}"

# JLink Installation
RUN wget -O JLink.deb --post-data $JLINK_LICENSE_ACCEPT "${JLINK_PKG_URL}" && \
    apt-get update && apt-get install --yes ./JLink.deb && \
    rm -f JLink.deb

# PlantUML Installation
RUN apt-get update && apt-get install -y --no-install-recommends \
        default-jre \
        && \
    apt-get autoremove -y && apt-get clean -y && \
    rm -rf /var/lib/apt/lists/* && \
    wget -O /tmp/plantuml.zip "${PLANTUML_PKG_URL}" && \
    unzip /tmp/plantuml.zip -d /opt/tools/plantuml && \
    ln -s /opt/tools/plantuml/plantuml-full /usr/bin/plantuml && \
    rm -f /tmp/plantuml.zip

# Pandoc Installation
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        texlive-latex-base \
        texlive-latex-extra \
        texlive-xetex \
        librsvg2-bin \
        && \
    apt-get autoremove -y && apt-get clean -y && \
    rm -rf /var/lib/apt/lists/* && \
    wget -O /tmp/pandoc.deb $PANDOC_PKG_URL && \
    dpkg -i /tmp/pandoc.deb && \
    rm -f /tmp/pandoc.deb

###############################################################################

# ccache configuration
RUN /usr/sbin/update-ccache-symlinks
ENV PATH="/usr/lib/ccache:${PATH}"

# Config git
RUN git config --global include.path "/home/${CONTAINER_USER}/.gitconfig"

###############################################################################

# VSCode Directories
ARG VSCODE_USER_DIR="/home/${CONTAINER_USER}/.vscode"
ARG VSCODE_EXT_DIR="${VSCODE_USER_DIR}/extensions"

# VSCode Extension Install
ARG VSCODE_INSTALL_EXT="code \
--user-data-dir ${VSCODE_USER_DIR} \
--extensions-dir ${VSCODE_EXT_DIR} \
--install-extension"

# VSCode Extension Install Hide Node Deprecation Warnings
ARG NODE_OPTIONS="--no-deprecation"

# VSCode Extension Install Hide Windows Subsystem Warning Prompt
ENV DONT_PROMPT_WSL_INSTALL="1"

# Create VSCode user config directory
RUN mkdir -p /home/${CONTAINER_USER}/.config/Code/User/

# Install vscode
RUN wget -O vscode.deb "${VSCODE_PKG_URL}" && \
    apt-get update && \
    apt-get install --yes ./vscode.deb && \
    rm -f vscode.deb

# Install vscode extensions from marketplace
RUN $VSCODE_INSTALL_EXT ms-vscode.cpptools@1.25.3 && \
    $VSCODE_INSTALL_EXT ms-vscode.cpptools-themes@2.0.0 && \
    $VSCODE_INSTALL_EXT ms-vscode.cmake-tools@1.20.53 && \
    $VSCODE_INSTALL_EXT espressif.esp-idf-extension@2.1.0 && \
    $VSCODE_INSTALL_EXT dan-c-underwood.arm@1.7.4 && \
    $VSCODE_INSTALL_EXT shardulm94.trailing-spaces@0.4.1 && \
    $VSCODE_INSTALL_EXT webfreak.debug@0.27.0 && \
    $VSCODE_INSTALL_EXT ZixuanWang.linkerscript@1.0.4 && \
    $VSCODE_INSTALL_EXT yzhang.markdown-all-in-one@3.6.3 && \
    $VSCODE_INSTALL_EXT DavidAnson.vscode-markdownlint@0.59.0 && \
    $VSCODE_INSTALL_EXT eamodio.gitlens@17.0.3 && \
    $VSCODE_INSTALL_EXT waderyan.gitblame@11.1.2 && \
    $VSCODE_INSTALL_EXT mhutchie.git-graph@1.30.0 && \
    $VSCODE_INSTALL_EXT donjayamanne.githistory@0.6.20 && \
    $VSCODE_INSTALL_EXT cschlosser.doxdocgen@1.4.0 && \
    $VSCODE_INSTALL_EXT streetsidesoftware.code-spell-checker@4.0.47 && \
    $VSCODE_INSTALL_EXT jebbs.plantuml@2.18.1 && \
    $VSCODE_INSTALL_EXT ms-python.python@2025.4.0 && \
    $VSCODE_INSTALL_EXT spmeesseman.vscode-taskexplorer@2.13.2

# Add VSCode default User configuration files
ADD --chown=${CONTAINER_USER}:${CONTAINER_USER} \
    container/vscode_config/*.json /home/${CONTAINER_USER}/.config/Code/User/

###############################################################################

# Change ownership of the home directory to the created user
RUN chown ${CONTAINER_USER}:${CONTAINER_USER} -R /home/${CONTAINER_USER}

# Set the container user that will use the image
USER ${CONTAINER_USER}
ENV HOME=/home/${CONTAINER_USER}
WORKDIR /home/${CONTAINER_USER}

# Launch VSCode at container logging
ENV CMD_CODE="code --disable-gpu"
CMD ["/bin/bash", "-c", "${CMD_CODE} & /bin/bash"]

###############################################################################
